---
pihosts:
  children:
    picontrollers:
      hosts:
        pi-1.local:
          ansible_host: 192.168.20.51
        pi-2.local:
          ansible_host: 192.168.20.52
      vars:
        pod_cidr: 10.0.0.0/8
        cluster_name: cluster.local
    piworkers:
      hosts:
        pi-3.local:
          ansible_host: 192.168.20.53
        pi-4.local:
          ansible_host: 192.168.20.54
        pi-5.local:
          ansible_host: 192.168.20.55
        pi-6.local:
          ansible_host: 192.168.20.56
        pi-7.local:
          ansible_host: 192.168.20.57
        pi-8.local:
          ansible_host: 192.168.20.58
  vars:
    ansible_user: root