- name: load new sysctl settings
  ansible.builtin.command: sysctl --system

- name: restart containerd
  ansible.builtin.systemd_service:
    name: containerd.service
    state: restarted

- name: remove containerd config file
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: apt-mark kubelet kubeadm kubectl
  ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl
